import './globals.css';
import { Suspense } from 'react';
import { Inter } from 'next/font/google';
import Loading from './loading';
import Navbar from '../src/components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Navbar />
      <Suspense fallback={<Loading />}>
        <body className={inter.className}>
          <>{children}</>
        </body>
      </Suspense>
    </>
  );
}
