import './globals.css'
import { Suspense } from 'react';
import { Inter } from 'next/font/google'
import Loading from './loading';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <p> layout on very pages tutaj dodać navbar footer itd</p>
      <Suspense fallback={<Loading/>}>
        <body className={inter.className}>{children}</body>
      </Suspense>
    </html>
  )
}
